AWSTemplateFormatVersion: '2010-09-09'
Description: A simple Hello World Serverless project
Resources:
  Realtime:
    Properties:
      CodeUri: s3://johnny-stocker/b1a8747b0b01c45e89772f83c65f0aba
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
