AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: A simple Hello World Serverless project
Resources:
  Realtime:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Timeout: 200
      Handler: index.handler
      CodeUri: .
      Environment:
        Variables:
          YAHOO_KEY: "dj0yJmk9VFlFUkJORW9XNjNNJmQ9WVdrOVluUlBZVlJZTXpRbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1kMA--"
          YAHOO_SECRET: "6b724a1f08684961bc8a05ecd44164633497ede3"
          ALPHA_VANTAGE_KEY: "SGNPZHDYMF74SXOU,GQ5JY788EPA5ZMDM"
          SLACK_API_TOKEN: "xoxb-263626238676-jnGkIGzDbj4DUqObtq0JDhg2"
